"""
VisionMate AI - Foundational Schema Contracts Module
Path: src/schemas/contracts.py

This module defines the standardized runtime data contracts used across the entire 
real-time assistive AI pipeline. To ensure the highest throughput and lowest latency 
on the real-time processing thread, all objects are constructed using Python's 
native dataclasses optimized with __slots__.

================================================================================
WHY __slots__ MATTERS FOR REAL-TIME COMPUTER VISION SYSTEMS:
================================================================================
1. Elimination of __dict__ Overhead:
   Normally, Python objects store their instance variables in a dynamic dictionary 
   (__dict__). This allows adding arbitrary attributes at runtime but introduces a 
   substantial memory footprint per object. In a 30+ FPS assistive CV system, 
   instantiating hundreds of bounding boxes, spatial analytics, and event nodes 
   every second leads to high memory churning. __slots__ dictates that instances 
   store attributes in a static array-like structure, drastically reducing memory usage.

2. Prevention of Garbage Collector Churn:
   Frequent allocation and deallocation of dynamic dictionaries on the hot-path 
   triggers frequent Python Garbage Collector (GC) runs. These small, non-deterministic 
   GC pauses can introduce micro-stutters, causing video frame drops. By using static 
   __slots__, GC overhead is virtually eliminated.

3. Accelerated Attribute Access:
   Accessing slot-based attributes is implemented in CPython as a direct array-offset 
   lookup in C, which is approximately 20-30% faster than looking up keys in a hash map 
   (__dict__).

================================================================================
WHY NORMALIZED SCHEMAS IMPROVE MAINTAINABILITY AND INTEROPERABILITY:
================================================================================
1. Clear Interface Boundaries:
   Standardized contracts decouple the core vision system. The Camera module produces 
   raw frames; the Detection module converts raw model inferences into 'Detection' instances; 
   the Logic module converts detections into 'HazardEvent' contracts; the Audio module speaks 
   'AudioSpeechRequest' specifications. If you swap the AI model (e.g. YOLOv8 for YOLOv10 
   or ONNX) or change the Audio framework, only the adapter translation layer changes.

2. Prevention of Magic Tuple / Dict Bugs:
   Relying on arbitrary dicts (e.g., d["bbox"]) or index arrays (e.g., det[0]) leads to 
   brittle code and silent bugs when coordinate formats change. Named schemas force strict, 
   type-checked contracts, enabling static analysers (Pyright/MyPy) to catch errors before runtime.
"""

from dataclasses import dataclass, field, asdict
from typing import Tuple, Optional
import time
import json


@dataclass(slots=True)
class Detection:
    """
    Standardized schema representing a single detected object in a camera frame.
    This acts as the data contract between the Detection module and the Spatial Logic module.
    
    Fields:
        class_name: The name of the detected object class (e.g., 'chair', 'vehicle', 'door').
        confidence: Model prediction confidence score from 0.0 to 1.0.
        bbox: Absolute pixel coordinates of the bounding box as (xmin, ymin, xmax, ymax).
        center_x: Pre-calculated horizontal center pixel of the bounding box.
        center_y: Pre-calculated vertical center pixel of the bounding box.
        width: Calculated width of the bounding box in pixels.
        height: Calculated height of the bounding box in pixels.
        estimated_distance: Mathematically estimated depth distance from the user in meters.
        spatial_zone: Classified horizontal region of the frame ('left', 'center', 'right').
        timestamp: The epoch timestamp when the video frame was originally captured.
    """
    class_name: str
    confidence: float
    bbox: Tuple[int, int, int, int]
    center_x: int
    center_y: int
    width: int
    height: int
    estimated_distance: float
    spatial_zone: str
    timestamp: float

    def to_dict(self) -> dict:
        """
        Converts the Detection dataclass instance into a clean Python dictionary.
        This provides a standardized format for serialization.
        """
        return asdict(self)

    def to_json(self) -> str:
        """
        Serializes the Detection object to a compact, standard JSON string.
        Perfect for WebSocket streaming, API responses, or writing telemetry logs.
        """
        return json.dumps(self.to_dict())


@dataclass(slots=True)
class HazardEvent:
    """
    Structured event contract generated by the Spatial Logic engine to represent
    active obstacles and safety concerns for the user.
    
    Fields:
        event_id: A unique string identifier (e.g. UUID) to track the event life-cycle.
        priority: Emergency hierarchy rating (1 = CRITICAL danger, 2 = Warning, 3 = Informative).
        message: Human-readable alert text (e.g., "Warning: pole directly ahead, 1 meter").
        source_detection: The corresponding Detection object that triggered this hazard.
                          Optional to support systemic alerts (e.g. "System active").
        created_at: Epoch timestamp of when this hazard was generated.
        expires_at: Epoch timestamp indicating when this hazard's relevance ends.
    """
    event_id: str
    priority: int
    message: str
    source_detection: Optional[Detection]
    created_at: float
    expires_at: float

    def to_dict(self) -> dict:
        """
        Converts the HazardEvent to a dictionary. Recursively converts the nested 
        source_detection dataclass into a dictionary if present.
        """
        return asdict(self)

    def to_json(self) -> str:
        """
        Serializes the HazardEvent and all nested attributes into a standard JSON string.
        Highly useful for sending real-time warnings over WebSockets to client apps.
        """
        return json.dumps(self.to_dict())

    def is_expired(self, current_time: Optional[float] = None) -> bool:
        """
        Checks if this safety warning has exceeded its valid lifetime.
        
        Args:
            current_time: Optional epoch timestamp to evaluate against. 
                          Defaults to current system time if not provided.
        """
        t = current_time if current_time is not None else time.time()
        return t >= self.expires_at


@dataclass(slots=True)
class AudioSpeechRequest:
    """
    Structured message contract dispatched to the background voice rendering queue.
    
    Fields:
        message: The exact spoken output text (e.g., "Step down close").
        priority: Urgency index. Audio system prioritizes higher values (lower index numbers).
        cooldown_seconds: The duration for which this exact message should be throttled 
                          to avoid rapid speech stuttering / audio repetition.
        interruptible: If True, this phrase can be cut off mid-speech by an incoming hazard of higher priority.
    """
    message: str
    priority: int
    cooldown_seconds: float
    interruptible: bool

    def to_dict(self) -> dict:
        """
        Converts the AudioSpeechRequest into a clean Python dictionary.
        """
        return asdict(self)


# ================================================================================
# EXAMPLE USAGE & CONTRACT WORKFLOW DEMONSTRATION
# ================================================================================
if __name__ == "__main__":
    print("--- VisionMate AI Schema Contract Demonstration ---")
    
    # 1. Simulate a frame capture timestamp
    frame_timestamp = time.time()
    
    # 2. Simulate object detector identifying an obstacle (e.g., Chair close ahead)
    # Bounding box represents [xmin, ymin, xmax, ymax]
    bbox_coordinates = (100, 150, 300, 450)
    
    # 3. Instantiate a standardized Detection object
    mock_detection = Detection(
        class_name="chair",
        confidence=0.89,
        bbox=bbox_coordinates,
        center_x=200,             # Pre-calculated: (xmin + xmax) // 2
        center_y=300,             # Pre-calculated: (ymin + ymax) // 2
        width=200,                # Pre-calculated: xmax - xmin
        height=300,               # Pre-calculated: ymax - ymin
        estimated_distance=1.2,   # Distance mapping based on spatial calculations
        spatial_zone="center",    # Bounding box center resides in middle partition
        timestamp=frame_timestamp
    )
    
    print("\n[STEP 1] Detection Created:")
    print(f"  Class: {mock_detection.class_name}")
    print(f"  Confidence: {mock_detection.confidence:.2%}")
    print(f"  Spatial Position: {mock_detection.spatial_zone} zone at {mock_detection.estimated_distance}m")
    
    # 4. Serialize Detection to JSON
    detection_json = mock_detection.to_json()
    print("\n[STEP 2] Serialized Detection JSON:")
    print(f"  {detection_json}")

    # 5. Spatial Logic processes detection and triggers a HazardEvent
    hazard_uuid = "e84a29a0-6c92-491c-8e3b-c2e399583b27"
    current_epoch = time.time()
    valid_lifespan = 1.5  # Hazard is considered active/valid for 1.5 seconds
    
    mock_hazard = HazardEvent(
        event_id=hazard_uuid,
        priority=1,  # Critical priority
        message="Warning: Chair directly ahead, 1.2 meters.",
        source_detection=mock_detection,
        created_at=current_epoch,
        expires_at=current_epoch + valid_lifespan
    )
    
    print("\n[STEP 3] HazardEvent Created:")
    print(f"  Event ID: {mock_hazard.event_id}")
    print(f"  Message: '{mock_hazard.message}'")
    print(f"  Is Expired: {mock_hazard.is_expired()}")
    
    # 6. Serialize HazardEvent (including nested structures) to JSON
    hazard_json = mock_hazard.to_json()
    print("\n[STEP 4] Serialized HazardEvent JSON:")
    # Formatting JSON output nicely for visual terminal display
    parsed_json = json.loads(hazard_json)
    print(json.dumps(parsed_json, indent=2))
    
    # 7. Convert hazard into an Audio speech dispatch request
    mock_speech_req = AudioSpeechRequest(
        message=mock_hazard.message,
        priority=mock_hazard.priority,
        cooldown_seconds=3.0,     # Don't repeat "Chair directly ahead" for at least 3 seconds
        interruptible=True        # Can be overridden if an even worse hazard (e.g. "Step down") is spotted
    )
    
    print("\n[STEP 5] AudioSpeechRequest Dispatched:")
    print(f"  Payload: {mock_speech_req.to_dict()}")
    print("--------------------------------------------------")
